### ISSUE TITLE
运行出现的问题

### ISSUE THREAD

**Issue by Crushmorry** [AnthonySun256/easy_games#2]
linux服务器运行产生错误 init_renderer: Assertion `rc == 0' failed.

**Comment by AnthonySun256** [comment]
请尝试 ``sudo apt-get install libsdl2-dev``

**Comment by Crushmorry** [comment]
已经安装了 还是没用

**Comment by AnthonySun256** [comment]
我无法复现这个问题，可能是缺少一些运行时库，您可以尝试使用 docker 或者虚拟机运行

**Comment by Crushmorry** [comment]
我用的云服务器运行的 无法运行

**Comment by AnthonySun256** [comment]
> 我用的云服务器运行的 无法运行
云服务器可能会缺少相关的显示组件，建议使用虚拟机尝试

**Comment by AnthonySun256** [comment]
> 我用的云服务器运行的 无法运行

云服务器可能会缺少一些显示相关的组件（毕竟云服务器很少需要有一个GUI），建议您使用虚拟机尝试

**Comment by Crushmorry** [comment]
谢谢
